version: '3'
services:
  movies:
    image: rahamshaik/paytmappmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: rahamshaik/paytmapptrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: rahamshaik/paytmappdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: rahamshaik/paytmapprecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
