version: '3.8'
services:
  movies:
    image: 8500100213/hotel:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: 8500100213/netflix:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: 8500100213/swiggy:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: 8500100213/zoomato:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
